name = "line-login"
type = "theme"
extension_points = ["app_embed", "section", "product", "block"]

[[metafields]]
namespace = "line-login"
key = "settings"

[[metafields]]
namespace = "daily-discounts"
key = "products"