services:
  - type: web
    name: shopify-collection-sorter
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run setup && npm run start
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src/prisma
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        value: "write_products,read_products,write_collection_listings,read_collection_listings"
