services:
  - type: web
    name: shopify-collection-sorter
    env: node
    plan: free
    buildCommand: npm ci && npm run build && npm run setup
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        value: "write_products,read_products,write_collection_listings,read_collection_listings"
