# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0aa9cbf0bbdf96808eba1e702874ab4"
application_url = "https://shopify-collection-sorter.onrender.com"
embedded = true
name = "Alpha-Dog"
handle = "alpha-dog-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_collection_listings,read_customers,write_customers"

[auth]
redirect_urls = [ "https://shopify-collection-sorter.onrender.com/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true

[app_proxy]
url = "https://shopify-collection-sorter.onrender.com"
subpath = "api"
prefix = "apps"
