# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0aa9cbf0bbdf96808eba1e702874ab4"
application_url = "https://example.com/"
embedded = true
name = "Alpha-Dog"
handle = "alpha-dog-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_collection_listings,read_collection_listings"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
